[package]
name = "infrastructures"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
axiom = { path = "../axiom" }
domain = { path = "../core/domain" }
use-cases = { path = "../core/use-cases", features = ["serde"] }

anyhow = { workspace = true }
ahash = { version = "0.8.12", optional = true }
argon2 = { version = "0.6.0-rc.1", features = ["std", "parallel", "zeroize"] }
async-trait = { workspace = true }
bon = { workspace = true }
chrono = { workspace = true }
csv = "1.4.0"
futures = { workspace = true }
fxhash = { version = "0.2.1", optional = true }
image = "0.25.9"
js-sys = "*"  # Manual version resolution?
jwt = { version = "0.16.0" }
metrohash = { version = "1.0.7", optional = true }
rayon = { workspace = true }
seahash = { version = "4.1.0", optional = true }
serde = { workspace = true }
serde_json = "1.0.45"
surrealdb = "2.4.0"
vec1 = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1.47.1", features = ["sync"] }
uuid = { version = "1.18.1", features = ["v7"] }
wasm-bindgen = { version = "=0.2.102", features = ["strict-macro"] }  # jsr:@deno/wasmbuild@0.19.3
wasm-bindgen-futures = "=0.4.52"  # jsr:@deno/wasmbuild@0.19.3

[target.'cfg(target_arch = "wasm32")'.dependencies]
# `getrandom` is a transitive dependency of `argon2`
# Using `getrandom` on `wasm32-unknown-unknown` requires
# explicitly enabling feature flag `wasm_js`
getrandom = { version = "*", features = ["wasm_js"]}
# Using `uuid` on `wasm32-unknown-unknown` requires
# a source of randomness from [`js`, `rng-getrandom`, `rng-rand`]
uuid = { version = "1.18.1", features = ["v7", "js"] }

[features]
default = ["ahash"]

ahash = ["dep:ahash"]
fxhash = ["dep:fxhash"]
metrohash = ["dep:metrohash"]
seahash = ["dep:seahash"]

[lints]
workspace = true
