name: "[cargo] Format & Lint"

on:
  workflow_call:

env:
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  ARGON2_SECRET_KEY: ${{ secrets.ARGON2_SECRET_KEY }}

jobs:
  cargo-fmt:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        channel:
          - nightly

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.channel }}
          components: rustfmt

      - run: cargo fmt --all -- --check

  cargo-clippy:
    needs:
      - cargo-fmt

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        channel:
          - nightly

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.channel }}
          components: clippy

      - run: cargo clippy --workspace --all-targets
