name: "[cargo] CI"

on:
  push:
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  format-and-lint:
    uses: ./.github/workflows/cargo-format-and-lint.yml

  build:
    needs:
      - format-and-lint
    uses: ./.github/workflows/cargo-build.yml

  test:
    needs:
      - format-and-lint
    uses: ./.github/workflows/cargo-test.yml

  dependencies-check:
    needs:
      - format-and-lint
      - build
      - test
    uses: ./.github/workflows/cargo-dependencies-check.yml
