name: "[cargo] Build"

on:
  workflow_call:

jobs:
  cargo-build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        channel:
          - stable
          - beta
          - nightly

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/cargo-load-env

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.channel }}

      - uses: Swatinem/rust-cache@v2

      - run: cargo check --workspace --all-targets
