name: "[cargo] Build"

on:
  workflow_call:

env:
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  ARGON2_SECRET_KEY: ${{ secrets.ARGON2_SECRET_KEY }}

  SURREALDB_ADDRESS: ${{ secrets.SURREALDB_ADDRESS }}
  SURREALDB_NAMESPACE: ${{ secrets.SURREALDB_NAMESPACE }}
  SURREALDB_DATABASE: ${{ secrets.SURREALDB_DATABASE }}

  SURREALDB_HOSTNAME: ${{ secrets.SURREALDB_HOSTNAME }}
  SURREALDB_INSTANCE_ID: ${{ secrets.SURREALDB_INSTANCE_ID }}
  SURREALDB_AUTH_TOKEN: ${{ secrets.SURREALDB_AUTH_TOKEN }}

jobs:
  cargo-build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        channel:
          - stable
          - beta
          - nightly

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.channel }}

      - uses: Swatinem/rust-cache@v2

      - run: cargo check --workspace --all-targets
